\documentclass{article}

\begin{document}

\title{VANGARD00076: Lung Cancer Trend Analysis using RNAseq Data}
\author{Quanhu Sheng}
\maketitle

<<gene, echo=FALSE, message=FALSE>>=
library(SAGx)
library(edgeR)
library(reshape)

c123<-c(1:7)

rdataname<-"pseudocounts.RData"

setwd("E:/sqh/programs/r/TrendAnalysis/VANGARD00076")

if(file.exists(rdataname)){
  load(rdataname)
}else{
  data<-read.table("count.tsv", sep="\t", header=T, row.names=1)
  
  #get group 1,2,3,6
  data1236<-data[,c(c123,17:19)]
  
  #normalize by edgeR
  y <- DGEList(counts=data1236)
  out <- equalizeLibSizes(y)
  pseudocounts<-data.frame(round(out$pseudo.counts))
  
  #get group 1,2,3 data for trend analysis
  data123<-pseudocounts[,c123]
  groups123<-as.ordered(substring(colnames(data123), 1,2))
  
  #trend analysis
  pvalue<-apply(data123, 1, function(x){
    p<-JT.test(data=t(as.matrix(x)),class=groups123)$p.value
  })

  trend_type<-apply(data123, 1, function(x){
    pd<-JT.test(data=t(as.matrix(x)),class=groups123,alternative="decreasing")$p.value
    pi<-JT.test(data=t(as.matrix(x)),class=groups123,alternative="increasing")$p.value
    if(pd < pi){
      return ("down")
    } else{
      return ("up")
    }
  })
  
  pseudocounts$trend_pvalue<-pvalue
  pseudocounts$trend_type<-trend_type
  
  save(pseudocounts, file=rdataname)
}

#due to limited sample size, fdr adjust result will be all 1.
pseudocounts$trend_pvalue<-round(pseudocounts$trend_pvalue, digits=4)
pseudocounts$count123<-apply(pseudocounts[,c123], 1, function(x){
  sum(x)
})

pseudocounts<-pseudocounts[order(pseudocounts$trend_pvalue, -pseudocounts$count123),]
write.csv(pseudocounts, file="trendby123.csv")

filtered<-pseudocounts[pseudocounts$trend_pvalue < 0.05,]
group1236<-substring(colnames(filtered)[1:10],1,2)
genenames<-rownames(filtered)

for(i in sequence(nrow(filtered))){
  x<-unlist(filtered[i,1:10])
  boxplot(x ~ group1236, main=paste0(genenames[i], " ; pvalue=", filtered[i,"trend_pvalue"] ))
}
@

\end{document}