\documentclass[a4paper]{article}
\textwidth 6.75in              % set dimensions before fancyhdr 
\textheight 9.5in
\topmargin -.875in
\oddsidemargin -.125in
\evensidemargin -.125in
 
\usepackage{hyperref}
\usepackage{subfigure}

\hypersetup{
    colorlinks=true, %set true if you want colored links
    linktoc=all,     %set to all if you want both sections and subsections linked
    linkcolor=blue,  %choose some color if you want links to stand out
}

\begin{document}
\title{Low miR-200 expression related drug selection}
\author{Quanhu Sheng, Christopher Pendleton}
\maketitle
\tableofcontents

<<setting, echo=FALSE>>=
opts_chunk$set(tidy=TRUE, fig.align='center', size='footnotesize', comment="", fig.width=5, fig.hight=5)
@

\newpage
\section{Purpose}
The miR-200 family contains miR-200a, miR-200b, miR-200c, miR-141, and miR-429. There are growing evidences to suggest that miR-200 microRNAs are involved in cancer metastasis. The project goal is using IC50 data to select drugs that target cell lines with low miR-200 expression.\\

\section{Selection of miR-200 expression related genes}
Here, TCGA paired BRCA miRNAseq/RNAseqV2 data containing 877 samples was used to find a gene set in which the expression level of the gene is highly correlated to the expression level of miR-200. \\

<<mirnaData, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results='asis', cache=TRUE>>=
source("e:/sqh/programs/r/mirna/chris_v2/common.r")
mirnaCount<-loadData("TCGA_mirnaseq_20130521_brca_count.csv")
target<-mirnaCount[row.names(mirnaCount) %in% targetnames,]
print(xtable(t(target)[c(1:5),], caption = "miRNAseq data", label = "tab:mirna"), include.rownames=T, caption.placement="top")
@

<<rnaseqData, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results='asis', cache=TRUE>>=
source("e:/sqh/programs/r/mirna/chris_v2/common.r")
rnaseqCount<-loadData("TCGA_rnaseqv2_20130521_brca_count.csv")
print(xtable(t(rnaseqCount)[c(1:5),c(1:7)], caption = "RNAseq data", label = "tab:rnaseq"), include.rownames=T, caption.placement="top")
@

Here is our workflow:
\begin{enumerate}
  \item 305 miRNAs observed in at least 90\% samples were used
  \item Ranks of all 305 miRNAs in each sample were calculated
  \item The ranks of each miR-200 cross all 877 samples were calculated based on the rank of that miR-200 in each sample
  \item 16044 genes observed in at least 90\% samples were used
  \item Ranks of all 16044 genes in each sample were calculated
  \item The ranks of each gene cross all 877 samples were calculated based on the rank of that gene in each sample
  \item Generized linear model was used to calculate the relation between each gene and all five miR-200
  \item pvalue were corrected by Bonferroni method
  \item 4140 genes were highly correlated with miR-200
\end{enumerate}

<<program, warning=FALSE, message=FALSE, cache=TRUE>>=
library(preprocessCore)
source("e:/sqh/programs/r/mirna/chris_v2/common.r")

#read mirna data
mirnaCount<-loadData("TCGA_mirnaseq_20130521_brca_count.csv")

#keep only observed in at least 90% samples
samplecount<-ncol(mirnaCount) * 0.9
keep<-rowSums(mirnaCount > 0) >= samplecount
mirnaCount<-mirnaCount[keep,]
mirnaUQ <- upperQuantile(mirnaCount)

#saveData(mirnaUQ,"TCGA_mirnaseq_20130521_brca_count_upperquantiled.csv")

targetCount<-data.frame(t(mirnaUQ[rownames(mirnaUQ) %in% targetnames,]))
colnames(targetCount)<-c("mir141", "mir200a", "mir200b", "mir200c", "mir429")
#summary(glm(mir141 ~ mir200a + mir200b + mir200c + mir429, data=targetCount ))
#summary(glm(mir200a ~ mir141 + mir200b + mir200c + mir429, data=targetCount ))
#summary(glm(mir200b ~ mir141 + mir200a + mir200c + mir429, data=targetCount ))
#summary(glm(mir200c ~ mir141 + mir200a + mir200b + mir429, data=targetCount ))
#summary(glm(mir429 ~ mir141 + mir200a + mir200b + mir200c, data=targetCount ))

result<-prcomp(t(targetCount))
plot(result$x[,1],result$x[,2],xlab="PC1",ylab="PC2",main="PCA")
text(result$x[1,1],result$x[1,2]-3000,labels=rownames(result$x)[1])
text(result$x[2,1]+60000,result$x[2,2],labels=rownames(result$x)[2])
text(result$x[3,1]+50000,result$x[3,2]+3000,labels=rownames(result$x)[3])
text(result$x[4,1]-15000,result$x[4,2]+4000,labels=rownames(result$x)[4])
text(result$x[5,1]+15000,result$x[5,2]+6000,labels=rownames(result$x)[5])

# #rank
# mirnaRank<-apply(mirnaCount, 2, function(x) rank(-x,ties.method="average"))
# saveData(mirnaRank,"TCGA_mirnaseq_20130521_brca_count_rankInSample.csv")
# 
# mirnaRank2<-apply(mirnaRank, 1, function(x) rank(x,ties.method="average"))
# saveData(mirnaRank2,"TCGA_mirnaseq_20130521_brca_count_rankCrossSample.csv")
# 
# #get target
# targetMirnaRank<-mirnaRank2[col.names(mirnaRank2) %in% targetnames,]
# mirna200<-apply(targetMirnaRank, 1, function(x) mean(x))

mirna200ab4<-apply(targetCount, 1, function(x) mean(x[c(2,3,5)]))
mirna<-cbind(targetCount,mirna200ab4)
#saveData(mirna,"TCGA_mirnaseq_20130521_brca_count_upperquantiled_merged.csv")

#read rnaseq data
rnaseqCount<-loadData("TCGA_rnaseqv2_20130521_brca_count.csv")

#keep only observed in at least 90% samples
samplecount<-ncol(rnaseqCount) * 0.9
keep<-rowSums(rnaseqCount > 0) >= samplecount
rnaseqCount<-rnaseqCount[keep,]
rnaseqUQ <- upperQuantile(rnaseqCount)
rnaseqUQ<-t(rnaseqUQ)
# 
# #rank
# rnaseqRank<-apply(rnaseqCount, 2, function(x) rank(-x,ties.method="average"))
# rnaseqv2<-apply(rnaseqRank, 1, function(x) rank(x,ties.method="average"))

#generized linear model
glmres<-apply(rnaseqUQ, 2, function(x){
  summ<-summary(glm(x ~ mirna[,1] + mirna[,4] + mirna[,6]))
  coeff<-coefficients(summ)
  return (coeff[,4])
})

glmres<-t(glmres)

glmminimum<-apply(glmres, 1, function(x){
  return (min(x[2:4]))
})

adjustpvalue<-p.adjust(glmminimum, method="bonferroni")

glmpre<-cbind(glmres, glmminimum, adjustpvalue)
colnames(glmpre)<-c("(Intercept)", colnames(mirna)[c(1,4,6)], "minimumPvalue", "adjustPvalue")

glmrank<-order(glmpre[,6])

glmfinal<-glmpre[glmrank,]

saveData(glmfinal, "TCGA_mir200_20130521_brca.csv")

head(glmfinal, 10)
@

\section{Selection of drugs targeting low miR-200 expressed cell lines}
The IC50 data was dowload from \url{http://www.cancerrxgene.org/downloads/}. IC\_50 means half maximal inhibitory (50\%) drug concentrations (natural log microMolar). The data includes cell line drug sensitivity data, mutations in cancer genes and tissue type (Table \ref{tab:ic50}). It includes 714 cell lines and 138 drugs. \\

<<ic50, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, results='asis', cache=TRUE>>=
source("e:/sqh/programs/r/mirna/chris/common.r")
ic50<-read.csv("gdsc_manova_input_w2.csv", head=T)
ic50<-ic50[-1,]
ic50slim<-ic50[1:4,c(1:3,77:78)]
print(xtable(ic50slim, caption = "IC50 data", label = "tab:ic50"), include.rownames=F, caption.placement="top")
@
\subsection{Using model to select low miR-200 expressed cell lines}
pending...
\subsection{Selection of drugs targeting selected cell lines }
pending...

\end{document}